// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkv4aKOrqGOTQj99uZLbMVFjzY8VLsDyE',
    appId: '1:63362279848:web:8db592a7a56498d3b6d59d',
    messagingSenderId: '63362279848',
    projectId: 'flutter-a5e4b',
    authDomain: 'flutter-a5e4b.firebaseapp.com',
    storageBucket: 'flutter-a5e4b.appspot.com',
    measurementId: 'G-SHPCDRJ506',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr39C9sgYHmtFh_G1U7SG2XIYdRCHrBsc',
    appId: '1:63362279848:android:c1beb691b05ea836b6d59d',
    messagingSenderId: '63362279848',
    projectId: 'flutter-a5e4b',
    storageBucket: 'flutter-a5e4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYgPqyUL6uagojzbyuiiHOsNuoLKyFJ9U',
    appId: '1:63362279848:ios:b189fe7d8ef77006b6d59d',
    messagingSenderId: '63362279848',
    projectId: 'flutter-a5e4b',
    storageBucket: 'flutter-a5e4b.appspot.com',
    iosClientId: '63362279848-9bj61s0e4bl0khbponld2ivet1e31deo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseBackend',
  );
}
